-- Local development seed. Runs on every `supabase db reset`.
--
-- Exists so the credit path is exercisable without completing a Google
-- OAuth round trip, and so a reset does not mean re-signing-in by hand.
-- Inserting into auth.users fires handle_new_user, which seeds the
-- profile, the balance, and the opening daily grant, so this one insert
-- gives a user with exactly one chop of credits.
--
-- Never applied to a hosted project: `supabase db push` only runs
-- migrations, not this file.

insert into auth.users (id, email, instance_id, aud, role)
values (
  '00000000-0000-4000-8000-000000000001',
  'dev@chop.local',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated'
);
-- Generated by worker/tests/make_seed_samples.py. Do not hand-edit.
--
-- A completed job with three real samples, cut from the drum fixture by
-- the same slice functions the pipeline uses. Lets screens 04 and 05 be
-- built against real audio and real peak data instead of mocks.

insert into jobs (
  id, user_id, source_type, source_path, prompt, status, stage,
  bpm, music_key, zip_path
)
values (
  '00000000-0000-4000-8000-000000000010',
  '00000000-0000-4000-8000-000000000001',
  'upload',
  'seed/drums_90.wav',
  'dusty, melancholy, chop the horns, keep the hiss',
  'done',
  'cutting',
  89,
  'C# major',
  'seed-samples/chop-ai-samples.zip'
)
on conflict (id) do nothing;

insert into samples (
  job_id, name, stem, start_ms, end_ms, bars, reason, storage_path,
  peaks, rank, recommended
)
values
  ('00000000-0000-4000-8000-000000000010', 'dust break', 'drums', 232, 2925, 1.0, 'the four-on-the-floor section, dry and close', 'seed-samples/01_dust_break_89bpm_Csmaj.wav', '[0.4064, 0.1061, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0358, 0.0, 0.0, 0.0, 0.0, 0.4064, 0.0842, 0.0, 0.0, 0.0, 1.0, 0.789, 0.0177, 0.0, 0.0, 0.0, 0.4064]'::jsonb, 1, true),
  ('00000000-0000-4000-8000-000000000010', 'kick one shot', 'drums', 232, 1578, 0.5, 'the cleanest single kick, no tail', 'seed-samples/02_kick_one_shot_89bpm_Csmaj.wav', '[0.4064, 0.2203, 0.1061, 0.0432, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.1637, 0.0358, 0.007, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]'::jsonb, 2, true),
  ('00000000-0000-4000-8000-000000000010', 'snare roll', 'drums', 905, 3599, 1.0, 'the backbeat with the room left on it', 'seed-samples/03_snare_roll_89bpm_Csmaj.wav', '[1.0, 0.0358, 0.0, 0.0, 0.0, 0.0, 0.4064, 0.0842, 0.0, 0.0, 0.0, 1.0, 0.789, 0.0177, 0.0, 0.0, 0.0, 0.4064, 0.3656, 0.0668, 0.0, 0.0, 0.0, 1.0]'::jsonb, 3, true)
on conflict do nothing;

insert into job_metrics (
  job_id, cache_hit, gpu_seconds, stage_ms, claude_input_tokens,
  claude_output_tokens, claude_cache_read_tokens, whisper_ran,
  analysis_window_ms, cost_micros
)
values (
  '00000000-0000-4000-8000-000000000010', false, 47.2,
  '{"pulled_audio":1900,"separated_stems":21400,"reading_instruments":9800,"finding_chops":4200,"cutting":2600}'::jsonb,
  5120, 1180, 1920, false, 120000, 66100
)
on conflict (job_id) do nothing;
