"""Cut the drum fixture into three samples and emit seed SQL.

Gives the sample screens real audio and real peak data to render before
any pipeline exists, so screens 04 and 05 can be built and screenshotted
rather than mocked. Uses the same slice functions the pipeline will, so
what the UI renders is genuinely what it will receive.

Run:  worker/.venv/bin/python worker/tests/make_seed_samples.py
"""

from __future__ import annotations

import json
import os

from worker.pipeline import analyze, slice as slicer

HERE = os.path.dirname(__file__)
FIXTURE = os.path.join(HERE, "fixtures", "drums_90.wav")
OUT_DIR = os.path.join(HERE, "..", "..", "public", "seed-samples")
SEED_SQL = os.path.join(HERE, "..", "..", "supabase", "seed_samples.sql")

USER_ID = "00000000-0000-4000-8000-000000000001"
JOB_ID = "00000000-0000-4000-8000-000000000010"

# Two bars, one bar, and two bars out of the fixture, so the cards show a
# spread of lengths the way a real chop would.
CHOPS = [
    ("dust break", "drums", 0.25, 3.0, "the four-on-the-floor section, dry and close"),
    ("kick one shot", "drums", 0.25, 0.5, "the cleanest single kick, no tail"),
    ("snare roll", "drums", 0.9, 3.5, "the backbeat with the room left on it"),
]


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)

    tempo = analyze.detect_tempo(FIXTURE)
    onsets = analyze.detect_onsets(FIXTURE)
    key = analyze.detect_key(FIXTURE)
    bpm = round(tempo.bpm)

    rows = []
    for index, (name, stem, start, end, reason) in enumerate(CHOPS, start=1):
        snapped = slicer.snap_to_onset(start, onsets, max_ms=80)
        q_start, q_end = slicer.quantize_to_bars(snapped, end, bpm=tempo.bpm)

        filename = slicer.sample_filename(index, name, tempo.bpm, key)
        dst = os.path.join(OUT_DIR, filename)
        slicer.cut(FIXTURE, dst, q_start, q_end)

        peaks = slicer.compute_peaks(dst, buckets=24)
        bars = round((q_end - q_start) / ((60.0 / tempo.bpm) * 4.0), 2)

        rows.append(
            {
                "name": name,
                "stem": stem,
                "start_ms": int(q_start * 1000),
                "end_ms": int(q_end * 1000),
                "bars": bars,
                "reason": reason,
                "storage_path": f"seed-samples/{filename}",
                "peaks": json.dumps(peaks),
                "rank": index,
                "recommended": "true",
            }
        )
        print(f"cut {filename}  {q_end - q_start:.2f}s  {bars} bars")

    values = ",\n  ".join(
        "("
        f"'{JOB_ID}', '{r['name']}', '{r['stem']}', {r['start_ms']}, {r['end_ms']}, "
        f"{r['bars']}, '{r['reason']}', '{r['storage_path']}', "
        f"'{r['peaks']}'::jsonb, {r['rank']}, {r['recommended']}"
        ")"
        for r in rows
    )

    sql = f"""-- Generated by worker/tests/make_seed_samples.py. Do not hand-edit.
--
-- A completed job with three real samples, cut from the drum fixture by
-- the same slice functions the pipeline uses. Lets screens 04 and 05 be
-- built against real audio and real peak data instead of mocks.

insert into jobs (
  id, user_id, source_type, source_path, prompt, status, stage,
  bpm, music_key, zip_path
)
values (
  '{JOB_ID}',
  '{USER_ID}',
  'upload',
  'seed/drums_90.wav',
  'dusty, melancholy, chop the horns, keep the hiss',
  'done',
  'cutting',
  {bpm},
  {f"'{key}'" if key else 'null'},
  'seed-samples/chop-ai-samples.zip'
)
on conflict (id) do nothing;

insert into samples (
  job_id, name, stem, start_ms, end_ms, bars, reason, storage_path,
  peaks, rank, recommended
)
values
  {values}
on conflict do nothing;

insert into job_metrics (
  job_id, cache_hit, gpu_seconds, stage_ms, claude_input_tokens,
  claude_output_tokens, claude_cache_read_tokens, whisper_ran,
  analysis_window_ms, cost_micros
)
values (
  '{JOB_ID}', false, 47.2,
  '{{"pulled_audio":1900,"separated_stems":21400,"reading_instruments":9800,"finding_chops":4200,"cutting":2600}}'::jsonb,
  5120, 1180, 1920, false, 120000, 66100
)
on conflict (job_id) do nothing;
"""

    with open(SEED_SQL, "w") as handle:
        handle.write(sql)

    zip_path = os.path.join(OUT_DIR, "chop-ai-samples.zip")
    slicer.build_zip(
        [os.path.join(OUT_DIR, f) for f in sorted(os.listdir(OUT_DIR)) if f.endswith(".wav")],
        zip_path,
    )

    print(f"wrote {SEED_SQL}")
    print(f"bpm {bpm}  key {key}")


if __name__ == "__main__":
    main()
